modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/EnvyWare/UltimatePokeBuilder/issues"
showAsResourcePack=false

[[mods]]
  modId="poketracker"
  version="1.1.2"
  displayName="PokeTracker"
  displayURL="https://discord.gg/7vqgtrjDGw"
  credits="Envyful"
  authors="Envyful"
  description='''
  TRACKER
  '''

  [[dependencies.poketracker]]
  modId="forge"
  mandatory=true
  versionRange="[47.1.28,)"
  ordering="NONE"
  side="BOTH"

  [[dependencies.poketracker]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.20.1,1.21)"
  ordering="NONE"
  side="BOTH"