modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/EnvyWare/UltimatePokeBuilder/issues"
showAsResourcePack=false

[[mods]]
  modId="poketracker"
  version="1.0.0"
  displayName="PokeTracker"
  displayURL="https://discord.gg/7vqgtrjDGw"
  credits="Envyful"
  authors="Envyful"
  description='''
  TRACKER
  '''

  [[dependencies.poketracker]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

  [[dependencies.poketracker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"